### ISSUE TITLE
'ofxGuiExtended2.h' file not found

### ISSUE THREAD

**Issue by RomainAl** [moebiussurfing/ofxChannelFx#2]
Hi ! Thx a lot, but when I'm trying examples it make me the same error :
<img width="1847" alt="Capture d’écran 2021-01-21 à 15 10 04" src="https://user-images.githubusercontent.com/60849348/105362246-f5e04780-5bfa-11eb-82a6-e1534c561069.png">
However, I have you ofxGUIExtended2 in my Addons folder...
Can you help me ? I'm a beginner in openframeworks... sorry !

**Comment by moebiussurfing** [comment]
hey @RomainAl , you are welcome. thanks for testing.

did you cloned the https://github.com/moebiussurfing/ofxGuiExtended2 repo ( my fork ) into OF/addons/,  right?

Then you need to run the Project Generator and open **example-BasicNoPresets**, and check that the addon **ofxGuiExtended2** is listed there. If not, you must add it manually from the list.
Usually if some addon it's listed into **example-BasicNoPresets/addons.make**, it should appear automatically.

Tell me if you get it to work.

EDIT: 
now I see that you are using the example with presets. This is more advanced and requires that you edit the ofxChannelFx.h file defines, as you can see on the top of the file. (This example requires also ofxPresetsManager)
I recommend you to start testing the **example-BasicNoPresets** first.

**Comment by RomainAl** [comment]
Hi @moebiussurfing ! Thx for your answer ! Finally it's works well when I add ofxGuiExtended2 in add-on list with Project Generator, contrary of your example addons.make !
Thanks for your awesome works ! See you in other issues soon :)

**Comment by moebiussurfing** [comment]
> Hi @moebiussurfing ! Thx for your answer ! Finally it's works well when I add ofxGuiExtended2 in add-on list with Project Generator, contrary of your example addons.make !
> Thanks for your awesome works ! See you in other issues soon :)

nice! Hope you like it. 

ofxGuiExtended2  do not where into addons.make because, this example-BasicPresets do not require ofxGuiExtended2.
It uses ofxImGui for the user control bc it uses my ofxPresetsManager.
That's why you need to edit ofxChannelFx.h manually depending on which example you want to run.
I am not an expert, but I read somewhere on the forum that new OF Project Generator version will allow to make some customizations like this one.  (maybe this is possible tuning addon_config.mk, but I am not sure)

PS:
I have seen some of your Vimeo music videos and looked cool. 
I have some coming add-ons to video processing (film fx using layers overlay-blending: retro VHS, lens flares, scratch, vintage frames...), another 3 channels fx/glitch bundle processor, and a 2 channels video mixer/blender) that maybe could be useful to you... I'll message you when they're ready.

**Comment by RomainAl** [comment]
Ok ! Yes, I like it :)
I will try your advice and tell you !

Also : Is that normal that there is no "save and load" on headers in your ofxGuiExtended2 "exampleAdvancedGui" ? There are in the ofxGuiExtended2 example... (there is no "Issues" tab in your ofxGuiExtended2 GitHub page...)

`I have seen some of your Vimeo music videos and looked cool.`
Oh thx !!

`I have some coming add-ons to video processing (film fx using layers overlay-blending: retro VHS, lens flares, scratch, vintage frames...), another 3 channels fx/glitch bundle processor, and a 2 channels video mixer/blender) that maybe could be useful to you... I'll message you when they're ready.`
Wow ! So beautiful ! I will use it for sure !!! :-D Thanks very much !!!

**Comment by moebiussurfing** [comment]
> Also : Is that normal that there is no "save and load" on headers in your ofxGuiExtended2 "exampleAdvancedGui" ? There are in the ofxGuiExtended2 example... (there is no "Issues" tab in your ofxGuiExtended2 GitHub page...)

yes, I disabled the save/load icons because I don't like the style and I do not need them. the settings are handled (autosave) by the addon (paramaters) or handled by ofxPresetsManager. (You can look into last commits to see how to enable again.)

**Comment by moebiussurfing** [comment]
hey @RomainAl , 
I just finished one of the add-ons:
https://github.com/moebiussurfing/ofxSurfingFX
